# Generated by Django 4.2.6 on 2023-11-04 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_rawmaterialcategory_productcollection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('number_in_stock', models.IntegerField()),
                ('darmaged', models.IntegerField()),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.RenameModel(
            old_name='RawMaterialCollection',
            new_name='IngredientCollection',
        ),
        migrations.DeleteModel(
            name='RawMaterial',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='store.ingredientcollection'),
        ),
    ]
